import { test, expect } from '@playwright/test';

// Real HTTP API + migrated PostgreSQL. No route interception in this suite.
test('gateway governance persists and governs real requests', async ({ page, request }) => {
  const root = '/api/v1/model-gateway';
  const stamp = Date.now(); const name = `联调-${stamp}`; const forbidden = `restricted-${stamp}`;
  const connectionResponse = await request.post(`${root}/connections`, { data: { name, protocol: 'demo' } });
  expect(connectionResponse.status()).toBe(201);
  const connection = await connectionResponse.json();
  const modelResponse = await request.post(`${root}/models`, { data: { name, connection_id: connection.id, model_name: 'demo', operations: ['chat'], tool_calling: true } });
  expect(modelResponse.status()).toBe(201);
  const model = await modelResponse.json();
  const profileResponse = await request.post(`${root}/profiles`, { data: { name, model_id: model.id, operation: 'chat' } });
  expect(profileResponse.status()).toBe(201);
  const profile = await profileResponse.json();
  expect((await request.post(`${root}/profiles/${profile.id}/publish`, { data: { revision: 1 } })).status()).toBe(200);
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('navigation').getByRole('button', { name: '模型网关' }).click();
  await page.getByLabel('搜索资源').fill(name);
  await page.locator('.gateway-card').click();
  await page.getByRole('combobox', { name: '输入文本审核', exact: true }).selectOption('sensitive_words');
  await page.getByRole('button', { name: '保存审核与定价', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('审核与定价已保存');
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '敏感词库', exact: true }).click();
  await page.getByRole('button', { name: '新增敏感词', exact: true }).click();
  await page.getByLabel('敏感词', { exact: true }).fill(forbidden);
  await page.getByLabel('敏感词类别', { exact: true }).fill('联调测试');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  await expect(page.getByRole('cell', { name: forbidden, exact: true })).toBeVisible();
  await page.getByLabel('待检测文本', { exact: true }).fill(forbidden.toUpperCase());
  await page.getByRole('button', { name: '检测文本', exact: true }).click();
  await expect(page.getByText('命中 1 项：联调测试')).toBeVisible();
  await page.getByRole('button', { name: '告警管理', exact: true }).click();
  await page.getByRole('button', { name: '新增告警规则', exact: true }).click();
  await page.getByLabel('名称', { exact: true }).fill(name);
  await page.getByLabel('触发条件').selectOption('content_blocked');
  await page.getByLabel('监控方案').selectOption(profile.id);
  await page.getByRole('button', { name: '保存', exact: true }).click();
  await expect(page.getByRole('cell', { name, exact: true })).toBeVisible();
  await page.getByRole('button', { name: '模型体验', exact: true }).click();
  await page.getByLabel('已发布方案').selectOption(profile.id);
  await page.getByRole('textbox', { name: '调用参数 JSON', exact: true }).fill(JSON.stringify({ operation: 'chat', messages: [{ role: 'user', content: forbidden }] }));
  await page.getByRole('button', { name: '调用模型', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('content_blocked_input');
  await page.getByRole('button', { name: '调用日志', exact: true }).click();
  await page.getByLabel('搜索调用日志').fill(name);
  await expect(page.getByRole('cell', { name: 'content_blocked_input', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '告警管理', exact: true }).click();
  await page.getByRole('button', { name: '告警事件', exact: true }).click();
  const eventRow = page.getByRole('row').filter({ has: page.getByRole('cell', { name, exact: true }) });
  await eventRow.getByRole('button', { name: '确认', exact: true }).click();
  await expect(eventRow).toContainText('已确认');
  await page.getByRole('button', { name: '访问密钥', exact: true }).click();
  await page.getByRole('button', { name: '新增访问密钥', exact: true }).click();
  await page.getByLabel('名称', { exact: true }).fill(name);
  await page.getByLabel('允许调用的方案').selectOption(profile.id);
  await page.getByRole('button', { name: '保存', exact: true }).click();
  const secret = await page.getByRole('textbox', { name: '新访问密钥', exact: true }).inputValue();
  expect(secret.startsWith('mgw_')).toBe(true);
  await page.keyboard.press('Escape');
  const invoke = { profile_id: profile.id, version: 1, payload: { operation: 'chat', messages: [{ role: 'user', content: 'hello' }] } };
  expect((await request.post(`${root}/external/invoke`, { data: invoke, headers: { Authorization: `Bearer ${secret}` } })).status()).toBe(200);
  const keyRow = page.getByRole('row').filter({ has: page.getByRole('cell', { name, exact: true }) });
  await keyRow.getByRole('button', { name: '停用', exact: true }).click();
  await expect(keyRow).toContainText('已停用');
  expect((await request.post(`${root}/external/invoke`, { data: invoke, headers: { Authorization: `Bearer ${secret}` } })).status()).toBe(401);
  await page.getByRole('button', { name: '配额管理', exact: true }).click();
  await expect(page.getByLabel('每分钟请求上限')).toHaveValue('1000');
  await page.getByRole('button', { name: '保存配额', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('配额已更新');
  await page.getByRole('button', { name: '监控概览', exact: true }).click();
  await expect(page.locator('.gateway-stat').filter({ hasText: '内容拦截' })).not.toContainText('—');
  await page.screenshot({ path: 'test-results/gateway-live-monitor.png', fullPage: true });
  expect(errors).toEqual([]);
});
