import { test, expect } from '@playwright/test';

test('model connection, publication, invocation and Agent binding', async ({ page }) => {
  const stamp = Date.now();
  const name = `测试模型-${stamp}`;
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('navigation').getByRole('button', { name: '模型网关' }).click();
  await page.getByRole('button', { name: '渠道管理', exact: true }).click();
  await page.getByRole('button', { name: '新建渠道', exact: true }).click();
  await page.getByLabel('配置 JSON').fill(JSON.stringify({ name, protocol: 'demo' }));
  const connectionResponse = page.waitForResponse(r => r.url().endsWith('/model-gateway/connections') && r.request().method() === 'POST');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  const connection = await (await connectionResponse).json() as { id: string };
  await expect(page.getByRole('status')).toContainText('已保存');
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '模型广场', exact: true }).click();
  await page.getByRole('button', { name: '新建模型', exact: true }).click();
  await page.getByLabel('配置 JSON').fill(JSON.stringify({ name, connection_id: connection.id, model_name: 'demo-v1', operations: ['chat'], tool_calling: true }));
  const modelResponse = page.waitForResponse(r => r.url().endsWith('/model-gateway/models') && r.request().method() === 'POST');
  await page.getByRole('button', { name: '保存', exact: true }).click();
  const model = await (await modelResponse).json() as { id: string };
  await expect(page.getByRole('status')).toContainText('已保存');
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '配置方案', exact: true }).click();
  await page.getByRole('button', { name: '新建配置方案', exact: true }).click();
  await page.getByLabel('配置 JSON').fill(JSON.stringify({ name, operation: 'chat', model_id: model.id, require_tools: true }));
  await page.getByRole('button', { name: '保存', exact: true }).click();
  await expect(page.getByRole('button', { name: '发布已保存方案' })).toBeEnabled();
  await page.getByRole('button', { name: '发布已保存方案' }).click();
  await expect(page.getByRole('status')).toContainText('已发布');
  await page.keyboard.press('Escape');
  await page.getByRole('button', { name: '模型体验', exact: true }).click();
  await page.getByLabel('已发布方案').selectOption({ label: `${name} · chat · v1` });
  await page.getByRole('button', { name: '调用模型', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('调用完成');
  await expect(page.locator('pre')).toContainText('"demo": true');
  await page.screenshot({ path: 'test-results/model-gateway-desktop.png', fullPage: true });
  await page.getByRole('navigation').getByRole('button', { name: 'Agent 管理' }).click();
  await page.getByLabel('名称', { exact: true }).fill(name);
  await page.getByLabel('Chat 模型方案').selectOption({ label: `${name} · 发布 v1` });
  await page.getByRole('button', { name: '保存草稿' }).click();
  await expect(page.getByRole('status')).toContainText('草稿已保存');
  await page.getByRole('button', { name: '发布已保存草稿' }).click();
  await expect(page.getByRole('status')).toContainText('已发布');
  expect(errors).toEqual([]);
});
