import { test, expect } from '@playwright/test';

test('knowledge, publication, conversation, confirmed ticket, handoff and evaluation', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  const stamp = Date.now();
  const kb = `浏览器知识库-${stamp}`;
  const agent = `浏览器客服-${stamp}`;
  const nav = async (name: string) => { await page.getByRole('navigation').getByRole('button', { name, exact: false }).click(); };
  await page.goto('/');
  await expect(page.getByRole('heading', { name: '平台总览', exact: true })).toBeVisible();
  await nav('知识库');
  await page.getByRole('textbox', { name: '知识库名称' }).fill(kb);
  await page.getByRole('button', { name: '创建', exact: true }).click();
  await page.getByLabel('标题', { exact: true }).fill('发货政策');
  await page.getByLabel('文本 / Markdown').fill('付款后 48 小时内发货，配送问题可申请客服工单。');
  await page.getByRole('button', { name: '保存并建立索引' }).click();
  await expect(page.getByRole('status')).toContainText('文档已建立索引');
  await page.getByLabel('检索问题').fill('发货');
  await page.getByRole('button', { name: '检索', exact: true }).click();
  await expect(page.locator('.search-hit')).toContainText('48 小时');
  await nav('Agent 管理');
  await page.getByRole('button', { name: '新增 Agent' }).click();
  await page.getByLabel('Agent 名称', { exact: true }).fill(agent);
  await page.locator('#agent-knowledge').getByRole('button', { name: '添加' }).click();
  await page.getByLabel(kb, { exact: true }).check();
  await page.getByRole('button', { name: '完成选择' }).click();
  await page.getByRole('button', { name: '保存草稿' }).click();
  await expect(page.getByRole('status')).toContainText('草稿已保存');
  await page.getByRole('button', { name: /发\s*布/, exact: true }).click();
  await expect(page.getByRole('status')).toContainText('已保存并发布');
  await page.getByRole('button', { name: '返回列表', exact: true }).click();
  await nav('会话工作台');
  await page.getByLabel('使用的 Agent').selectOption({ label: `${agent} · v1` });
  await page.getByRole('button', { name: '新建会话' }).click();
  await page.getByLabel('消息内容').fill('什么时候发货？');
  await page.getByRole('button', { name: '发送消息' }).click();
  await expect(page.locator('.message.assistant')).toContainText('48 小时', { timeout: 20000 });
  await expect(page.locator('.trace')).toContainText('knowledge.retrieved');
  await page.getByLabel('消息内容').fill('请创建配送工单');
  await page.getByRole('button', { name: '发送消息' }).click();
  await expect(page.getByRole('button', { name: '确认创建' })).toBeEnabled({ timeout: 20000 });
  await page.getByRole('button', { name: '确认创建' }).click();
  await expect(page.getByRole('status')).toContainText('工单已创建');
  await expect(page.locator('.message.system')).toContainText('已创建');
  await page.getByRole('button', { name: '转人工', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('人工队列');
  const conversation = await page.locator('.list-item.selected strong').innerText();
  await nav('人工协同');
  const card = page.locator('.service-card').filter({ hasText: conversation });
  await card.getByRole('button', { name: '接管', exact: true }).click();
  await expect(card.getByRole('button', { name: '结束并恢复 Agent' })).toBeVisible();
  await nav('会话工作台');
  await page.getByRole('button').filter({ hasText: conversation }).click();
  await page.getByLabel('消息内容').fill('人工客服已为您核查配送信息。');
  await page.getByRole('button', { name: '人工回复', exact: true }).click();
  await expect(page.locator('.message.human')).toContainText('人工客服已为您核查');
  await nav('人工协同');
  await card.getByRole('button', { name: '结束并恢复 Agent' }).click();
  await expect(page.getByRole('status')).toContainText('已恢复');
  await nav('质量评测');
  await page.getByLabel('待评测的发布版本').selectOption({ label: `${agent} · v1` });
  await page.getByLabel('用例名称').fill('退货知识问答');
  await page.getByLabel('用户输入', { exact: true }).fill('退货政策');
  await page.getByLabel('预期包含文本（每行一项）').fill('七天');
  await page.getByRole('button', { name: '保存用例' }).click();
  await expect(page.getByRole('status')).toContainText('用例已保存');
  await page.getByRole('button', { name: '运行评测' }).click();
  await expect(page.locator('.report')).toContainText('1/1 通过', { timeout: 20000 });
  for (const name of ['工具目录', '服务工单', '渠道接入', '运行与审计', '访问与策略', '平台总览']) {
    await nav(name);
    await expect(page.getByRole('heading', { name, exact: true, level: 1 })).toBeVisible();
    await expect(page.locator('.alert.error')).toHaveCount(0);
  }
  await page.screenshot({ path: 'test-results/platform-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: 'test-results/platform-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  expect(errors).toEqual([]);
});
