import {useEffect,useState} from 'react';
import {Alert,App,Button,Card,Checkbox,Form,Input,Modal,Pagination,Select,Space,Switch,Table,Tag,Typography} from 'antd';
import {t,dateTime} from '../../i18n';
import {post,put} from '../../shared/api/client';
import {useAccess,useResource} from '../../shared/components/ui';
import {ROOT,type Application} from './OpenPlatformPage';
const errorOf=(e:unknown)=>e instanceof Error?e.message:String(e);
export function appBody(app:Application){return {name:app.name,description:app.description,enabled:app.enabled,agent_ids:app.agent_ids,rpm:app.rpm,max_concurrency:app.max_concurrency,revision:app.revision,agent_versions:app.agent_versions||{},knowledge_base_ids:app.knowledge_base_ids||[]};}
function Version({id,name,value,disabled,onChange}:{id:string;name:string;value?:number;disabled:boolean;onChange:(version?:number)=>void}){
 const versions=useResource<{version:number}[]>(`/open-platform/agents/${id}/versions`);
 return <Form.Item label={name} extra={versions.error}><Select aria-label={name} loading={versions.loading} disabled={disabled} value={value||0} onChange={v=>onChange(v||undefined)} options={[{value:0,label:t('跟随当前发布版本')},...(versions.data||[]).map(v=>({value:v.version,label:`v${v.version}`}))]}/></Form.Item>;
}
export function Integrations({app,agents,saved}:{app:Application;agents:{id:string;name:string}[];saved:()=>void}){
 const {admin}=useAccess();const {message}=App.useApp();const [pins,setPins]=useState(app.agent_versions||{});const [bases,setBases]=useState(app.knowledge_base_ids||[]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const catalog=useResource<{id:string;name:string}[]>('/open-platform/knowledge-bases');
 return <div className="op-stack"><Card title={t('Agent 版本固定')}><p className="op-muted">{t('固定版本后，新运行使用指定版本；已开始的运行保持原版本。')}</p><Form layout="vertical">{app.agent_ids.map(id=><Version key={id} id={id} name={agents.find(a=>a.id===id)?.name||id} value={pins[id]} disabled={!admin} onChange={v=>setPins(p=>{const next={...p};if(v)next[id]=v;else delete next[id];return next;})}/>)}</Form></Card>
 <Card title={t('知识库同步授权')}><Alert showIcon type="info" title={t('授权后允许应用同步文档并发布整个知识库。')} description={t('同步文本或 Markdown 先生成草稿，显式发布后进入检索；索引状态可通过任务接口查询。')}/><Select aria-label={t('知识库同步授权')} style={{width:'100%'}} mode="multiple" disabled={!admin} loading={catalog.loading} value={bases} onChange={setBases} options={(catalog.data||[]).map(b=>({value:b.id,label:b.name}))}/>{(error||catalog.error)&&<Alert type="error" title={error||catalog.error}/>}<Button style={{marginTop:20}} type="primary" disabled={!admin} loading={busy} onClick={async()=>{setBusy(true);setError('');try{await put(`${ROOT}/${app.id}`,{...appBody(app),agent_versions:pins,knowledge_base_ids:bases});message.success(t('已保存'));saved();}catch(e){setError(errorOf(e));}finally{setBusy(false);}}}>{t('保存集成配置')}</Button></Card>
 <Card title={t('SDK 下载')}><p>{t('SDK 用于企业服务端，提供会话、事件流、知识同步与 Webhook 验签。')}</p><Space><Button href="/sdk/nexusdesk-python.zip" download>Python SDK · 0.2.0</Button><Button href="/sdk/nexusdesk-javascript.zip" download>Node.js SDK · 0.2.0</Button></Space><pre className="op-code">{'# Python 3.10+\npip install ./python\nfrom nexusdesk import Client, verify_webhook\nclient = Client("https://your-host/openapi/v1", "<APP_KEY>", "employee-001")\n\n# Node.js 20+ (local package)\nnpm install ./javascript\nimport {Client, verifyWebhook} from "@nexusdesk/enterprise";'}</pre></Card></div>;
}
interface Hook {url:string;enabled:boolean;revision:number}
interface Delivery {id:string;event_type:string;resource_id:string;status:string;attempts:number;http_status:number|null;error_code:string|null;created_at:string}
export function WebhookPanel({app}:{app:Application}){
 const {admin}=useAccess();const {message}=App.useApp();const config=useResource<Hook|null>(`${ROOT}/${app.id}/webhook`);const [form]=Form.useForm();const [page,setPage]=useState(1);const deliveries=useResource<{items:Delivery[];total:number}>(`${ROOT}/${app.id}/deliveries?page=${page}`,5000);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [secret,setSecret]=useState('');
 useEffect(()=>{if(!config.loading)form.setFieldsValue({url:config.data?.url||'',enabled:config.data?.enabled||false,rotate_secret:false});},[config.data,config.loading,form]);
 return <div className="op-stack"><Card title={t('Webhook 回调')}><Alert showIcon type="info" title={t('接收运行结束与知识发布结果，失败自动重试，最多 5 次。')} description={t('修改回调配置会取消旧配置的待投递事件；在途请求可能已发送。接收端需按 event_id 去重。')}/>{(error||config.error)&&<Alert type="error" title={error||config.error}/>}
 <Form form={form} layout="vertical" disabled={!admin||config.loading} onFinish={async values=>{setBusy(true);setError('');try{const result=await put<Hook&{secret?:string}>(`${ROOT}/${app.id}/webhook`,{...values,revision:config.data?.revision||0});if(result.secret)setSecret(result.secret);config.refresh();deliveries.refresh();message.success(t('已保存'));}catch(e){setError(errorOf(e));}finally{setBusy(false);}}}>
 <Form.Item name="url" label={t('回调地址')} rules={[{required:true},{type:'url'}]}><Input placeholder="https://internal.example.com/hooks/nexusdesk" maxLength={2000}/></Form.Item><Form.Item name="enabled" label={t('启用回调')} valuePropName="checked"><Switch/></Form.Item>{config.data&&<Form.Item name="rotate_secret" valuePropName="checked"><Checkbox>{t('轮换签名密钥')}</Checkbox></Form.Item>}<Button type="primary" htmlType="submit" loading={busy}>{t('保存回调配置')}</Button></Form>
 <p className="op-muted">{t('签名采用 HMAC-SHA256，验签原文为时间戳、英文句点和原始请求体。请使用 SDK 验签并限制时间窗口。')}</p><code>X-Webhook-ID / X-Webhook-Timestamp / X-Webhook-Signature</code></Card>
 <Card title={t('投递记录')} extra={<Button onClick={deliveries.refresh}>{t('刷新')}</Button>}>{deliveries.error&&<Alert type="error" title={deliveries.error}/>}<Table<Delivery> rowKey="id" loading={deliveries.loading} dataSource={deliveries.data?.items||[]} pagination={false} scroll={{x:850}} expandable={{expandedRowRender:r=><Space direction="vertical"><Typography.Text copyable>Event ID: {r.id}</Typography.Text><Typography.Text copyable>Resource ID: {r.resource_id}</Typography.Text><span>{r.error_code||'—'}</span></Space>}} columns={[{title:t('时间'),dataIndex:'created_at',render:dateTime},{title:t('事件类型'),dataIndex:'event_type'},{title:t('状态'),dataIndex:'status',render:v=><Tag color={v==='succeeded'?'success':v==='failed'?'error':'default'}>{v}</Tag>},{title:t('尝试次数'),dataIndex:'attempts'},{title:'HTTP',dataIndex:'http_status',render:v=>v||'—'},{title:t('操作'),render:(_,r)=><Button disabled={!admin||r.status!=='failed'||!config.data?.enabled||!app.enabled} onClick={async()=>{try{await post(`${ROOT}/${app.id}/deliveries/${r.id}/retry`);deliveries.refresh();}catch(e){setError(errorOf(e));}}}>{t('重新投递')}</Button>}]}/><Pagination current={page} pageSize={20} total={deliveries.data?.total||0} onChange={setPage} showSizeChanger={false}/></Card>
 <Modal open={!!secret} destroyOnHidden title={t('请保存签名密钥')} onCancel={()=>setSecret('')} footer={<Button onClick={()=>setSecret('')}>{t('我已保存')}</Button>}><Alert type="warning" title={t('关闭后无法再次查看完整密钥。')}/><Typography.Paragraph copyable className="op-secret">{secret}</Typography.Paragraph></Modal></div>;
}
