import { useEffect, useRef, useState } from 'react';
import { Alert, Button, Card, Form, Input, Modal, Select, Space, Switch, Table, Tabs, Tag, Typography } from 'antd';
import { ToolOutlined } from '@ant-design/icons';
import { t } from '../../i18n';
import { roundAnswer, Trace, usePacedText } from '../../shared/components/ui';
import type { Application } from './OpenPlatformPage';

export function IntegrationDocs({app}:{app:Application}) {
  const base=window.location.origin+'/openapi/v1';const agent=app.agent_ids[0]||'<AGENT_ID>';
  const curl=`curl '${base}/conversations' \\\n  -H 'Authorization: Bearer <APP_KEY>' \\\n  -H 'X-External-User-ID: employee-001' \\\n  -H 'Content-Type: application/json' \\\n  -d '{"agent_id":"${agent}","external_session_id":"session-001"}'\n\ncurl -N '${base}/conversations/<CONVERSATION_ID>/messages' \\\n  -H 'Authorization: Bearer <APP_KEY>' \\\n  -H 'X-External-User-ID: employee-001' \\\n  -H 'Idempotency-Key: message-001' \\\n  -H 'Content-Type: application/json' \\\n  -d '{"message":"Hello","stream":true}'`;
  const python=`import requests\n\nBASE = "${base}"\nKEY = "<APP_KEY>"\nh = {"Authorization": f"Bearer {KEY}",\n     "X-External-User-ID": "employee-001"}\nr = requests.post(BASE + "/conversations", headers=h, json={\n    "agent_id": "${agent}", "external_session_id": "session-001"}, timeout=30)\nr.raise_for_status()\ncid = r.json()["conversation_id"]\nr = requests.post(f"{BASE}/conversations/{cid}/messages",\n    headers={**h, "Idempotency-Key": "message-001"},\n    json={"message": "Hello", "stream": False}, timeout=40)\nr.raise_for_status()\nrun = r.json()\nprint(run)\n# HTTP 202: GET /runs/{run['id']} to poll, or GET /runs/{run['id']}/events.\n# A timeout retry MUST reuse the same Idempotency-Key and body.`;
  const js=`// Server-side JavaScript\nconst base = '${base}';\nconst headers = {Authorization: 'Bearer <APP_KEY>',\n  'X-External-User-ID': 'employee-001', 'Content-Type': 'application/json'};\nasync function checked(url, init) {\n  const r = await fetch(url, init);\n  if (!r.ok) throw new Error(await r.text());\n  return r;\n}\nconst c = await checked(base + '/conversations', {method: 'POST', headers,\n  body: JSON.stringify({agent_id: '${agent}', external_session_id: 'session-001'})});\nconst {conversation_id} = await c.json();\nconst r = await checked(base + '/conversations/' + conversation_id + '/messages', {\n  method: 'POST', headers: {...headers, 'Idempotency-Key': 'message-001'},\n  body: JSON.stringify({message: 'Hello', stream: true})});\n// Chunks are not SSE message boundaries; accumulate decoded text before parsing.\nconst decoder = new TextDecoder();\nfor await (const chunk of r.body) process.stdout.write(decoder.decode(chunk, {stream: true}));`;
  return <div className="op-stack"><Alert type="info" showIcon title={t('三步接入：授权 Agent → 创建密钥 → 从企业服务端调用。')} description={t('外部用户标识由企业服务端在完成用户认证后传入；不要将应用密钥嵌入公开网页或移动端。')}/>
    <Card title={t('接入约定')}><Typography.Paragraph copyable><code>{base}</code></Typography.Paragraph><p><code>Authorization: Bearer &lt;APP_KEY&gt;</code></p><p><code>X-External-User-ID: employee-001</code></p><p>{t('会话按应用和外部用户隔离。同一外部会话标识可安全重试创建；发送消息必须携带唯一的 Idempotency-Key，重试同一消息时保持不变。')}</p><p>{t('SSE 返回运行进度事件，并在 run.completed 中返回完整回答；当前不逐字输出模型内容。断线后使用 Last-Event-ID 重连事件接口。')}</p><p>{t('普通调用最多等待 30 秒，未完成时返回 HTTP 202 和运行 ID。关闭事件流不会取消运行，需要显式调用取消接口。')}</p><p>{t('所有公开接口共享应用请求配额，轮询也计入；超限返回 429 和 Retry-After。并发限制包含排队和运行中的任务。')}</p>
      <Table pagination={false} rowKey="path" size="small" dataSource={[
        {method:'GET',path:'/agents',usage:t('查询已授权 Agent')},{method:'POST',path:'/conversations',usage:t('创建或获取会话')},{method:'GET',path:'/conversations/{id}/messages',usage:t('分页查询消息：after、limit')},{method:'POST',path:'/conversations/{id}/messages',usage:t('发送消息：message、stream、wait_seconds')},{method:'GET',path:'/runs/{id}',usage:t('查询运行结果')},{method:'GET',path:'/runs/{id}/events',usage:t('事件流与断线重连')},{method:'POST',path:'/runs/{id}/cancel',usage:t('取消运行')}
      ]} columns={[{title:t('方法'),dataIndex:'method',width:80,render:v=><Tag>{v}</Tag>},{title:t('路径'),dataIndex:'path',render:v=><code>{v}</code>},{title:t('说明'),dataIndex:'usage'}]} scroll={{x:680}}/>
      <p><code>{'{"error":{"code":"agent_not_authorized"},"request_id":"..."}'}</code></p><p>{t('401 密钥无效或过期；403 应用停用或未授权；404 资源不可见；409 会话忙或幂等冲突；422 参数错误；429 限流；503 服务暂不可用。')}</p>
    </Card><Card title={t('知识同步接口')}><p>{t('应用只能管理自己同步的文档。更新和删除需携带 expected_version；发布需使用 Idempotency-Key。')}</p><Table size="small" pagination={false} rowKey="path" scroll={{x:640}} dataSource={[
      {method:'GET',path:'/knowledge-bases',usage:t('知识库同步授权')},
      {method:'GET',path:'/knowledge-bases/{id}/documents?offset=0',usage:t('知识同步接口')},
      {method:'PUT',path:'/knowledge-bases/{id}/documents/{external_id}',usage:t('同步文档草稿')},
      {method:'DELETE',path:'/knowledge-bases/{id}/documents/{external_id}?expected_version=1',usage:t('移除同步文档关联')},
      {method:'POST',path:'/knowledge-bases/{id}/publish',usage:t('发布知识库并生成任务')},
      {method:'GET',path:'/knowledge-tasks/{task_id}',usage:t('查询知识发布任务')}
    ]} columns={[{title:t('方法'),dataIndex:'method'},{title:t('路径'),dataIndex:'path',render:v=><code>{v}</code>},{title:t('说明'),dataIndex:'usage'}]}/><pre className="op-code">{'PUT body: {"title":"Handbook","content":"# Welcome","expected_version":0}\nPOST /publish header: Idempotency-Key: publish-001\nGET /knowledge-tasks/{task_id} → queued / running / completed / failed / cancelled'}</pre><Space><Button href="/sdk/nexusdesk-python.zip" download>Python SDK</Button><Button href="/sdk/nexusdesk-javascript.zip" download>Node.js SDK</Button></Space></Card><Card title={t('调用示例')}><Tabs items={[['cURL',curl],['Python',python],['JavaScript',js]].map(([label,code])=>({key:label,label,children:<Typography.Paragraph copyable={{text:code}}><pre className="op-code">{code}</pre></Typography.Paragraph>}))}/></Card>
  </div>;
}

interface Run {id:string;status:string;output:string|null;error_code:string|null}
export function Debugger({app,agents}:{app:Application;agents:{id:string;name:string}[]}) {
  const [key,setKey]=useState('');const [user,setUser]=useState('debug-user');const [session,setSession]=useState<string>(()=>crypto.randomUUID());const [agent,setAgent]=useState(app.agent_ids[0]);const [text,setText]=useState('');const [stream,setStream]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [answer,setAnswer]=useState('');const [live,setLive]=usePacedText();const [traceRun,setTraceRun]=useState('');const [progress,setProgress]=useState<string[]>([]);const [run,setRun]=useState<Run|null>(null);const [requestId,setRequestId]=useState('');
  const controller=useRef<AbortController|null>(null);const active=useRef<{key:string;user:string}|null>(null);const pending=useRef<{hash:string;id:string}|null>(null);const runId=useRef('');
  // Per-round text from model.delta. A round that ends in tool calls was the model
  // thinking out loud, so it is marked and ignored: only the final answer round is
  // shown. Rounds are marked rather than deleted because a delta can arrive after
  // its round's boundary, and deleting would let it reappear.
  const rounds=useRef<Map<number,{text:string;toolCalls?:number}>>(new Map());
  const liveAnswer=()=>roundAnswer([...rounds.current.values()]);
  useEffect(()=>()=>{controller.current?.abort();},[]);
  function headers(identity={key,user}) {return {'Content-Type':'application/json',Authorization:'Bearer '+identity.key,'X-External-User-ID':identity.user};}
  async function checked(path:string,init:RequestInit) {const r=await fetch('/openapi/v1'+path,init);setRequestId(r.headers.get('X-Request-ID')||'');if(!r.ok){const data=await r.json();throw Error(`${r.status} · ${data.error?.code||'request_failed'}`);}return r;}
  function completed(data:Run){setRun(data);setAnswer(data.output||'');setLive(data.output||'');if(data.error_code)setError(data.error_code);}
  async function send(){if(busy)return;setBusy(true);setError('');setAnswer('');setLive('');rounds.current.clear();setProgress([]);setRun(null);runId.current='';active.current={key,user};const abort=new AbortController();controller.current=abort;
    try{const common={headers:headers(),signal:abort.signal};const c=await checked('/conversations',{...common,method:'POST',body:JSON.stringify({agent_id:agent,external_session_id:session})});const {conversation_id:cid}=await c.json();
      const hash=JSON.stringify([key,user,cid,text]);if(pending.current?.hash!==hash)pending.current={hash,id:crypto.randomUUID()};
      const r=await checked(`/conversations/${cid}/messages`,{...common,method:'POST',headers:{...headers(),'Idempotency-Key':pending.current.id},body:JSON.stringify({message:text,stream})});
      if(!stream){const data=await r.json();runId.current=data.id;completed(data);if(['completed','failed','cancelled'].includes(data.status))pending.current=null;return;}
      const reader=r.body!.getReader();const decoder=new TextDecoder();let buffer='';
      while(true){const {done,value}=await reader.read();buffer+=decoder.decode(value,{stream:!done});let boundary:number;
        while((boundary=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);const lines=block.split('\n');const type=lines.find(l=>l.startsWith('event:'))?.slice(6).trim();const raw=lines.filter(l=>l.startsWith('data:')).map(l=>l.slice(5).trimStart()).join('\n');if(!type||!raw)continue;const data=JSON.parse(raw);if(data.run_id)runId.current=data.run_id;if(type==='model.delta'){if(data.text){const cur=rounds.current.get(data.round)||{text:''};rounds.current.set(data.round,{...cur,text:cur.text+data.text});setLive(liveAnswer());}continue;}if(type==='model.completed'){const cur=rounds.current.get(data.round)||{text:''};rounds.current.set(data.round,{...cur,toolCalls:data.tool_calls||0});setLive(liveAnswer());continue;}setProgress(p=>[...p.slice(-49),type]);if(type==='error')throw Error(data.code);if(['run.completed','run.failed','run.cancelled'].includes(type)){completed(data);pending.current=null;}}
        if(done)break;
      }
    }catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);controller.current=null;}}
  async function cancel(){try{if(runId.current&&active.current){const r=await checked(`/runs/${runId.current}/cancel`,{method:'POST',headers:headers(active.current)});completed(await r.json());}controller.current?.abort();}catch(e){setError(String(e));}}
  async function refresh(){if(!runId.current||!active.current)return;try{const r=await checked(`/runs/${runId.current}`,{headers:headers(active.current)});const data=await r.json();completed(data);if(['completed','failed','cancelled'].includes(data.status))pending.current=null;}catch(e){setError(String(e));}}
  return <div className="op-debug"><Card title={t('在线调试')}><Alert type="info" showIcon title={t('使用真实应用密钥调试，调用会计入配额并生成日志。')} description={t('密钥仅保留在当前页面内存中，离开页面后清除。')}/><Form layout="vertical" onFinish={send}>
    <Form.Item label={t('应用密钥')} htmlFor="op-debug-key" required><Input.Password id="op-debug-key" value={key} onChange={e=>setKey(e.target.value)} autoComplete="off" disabled={busy} placeholder="opk_..."/></Form.Item>
    <Form.Item label={t('授权 Agent')} required><Select value={agent} onChange={v=>{setAgent(v);setSession(crypto.randomUUID());}} disabled={busy} options={agents.filter(a=>app.agent_ids.includes(a.id)).map(a=>({value:a.id,label:a.name}))}/></Form.Item>
    <div className="op-form-row"><Form.Item label={t('外部用户标识')} required><Input value={user} maxLength={128} disabled={busy} onChange={e=>setUser(e.target.value)}/></Form.Item><Form.Item label={t('外部会话标识')} required><Input value={session} maxLength={128} disabled={busy} onChange={e=>setSession(e.target.value)}/></Form.Item></div>
    <Form.Item label={t('消息')} htmlFor="op-debug-message" required><Input.TextArea id="op-debug-message" rows={4} value={text} maxLength={8000} disabled={busy} onChange={e=>setText(e.target.value)}/></Form.Item><Form.Item label={t('SSE 事件流')}><Switch checked={stream} onChange={setStream} disabled={busy}/></Form.Item>
    <Space wrap><Button type="primary" htmlType="submit" loading={busy} disabled={!app.enabled||!key.trim()||!agent||!user.trim()||!session.trim()||!text.trim()}>{t('发送消息')}</Button><Button disabled={!busy&&!runId.current} onClick={cancel}>{t('取消运行')}</Button><Button disabled={busy||!runId.current} onClick={refresh}>{t('查询运行结果')}</Button><Button disabled={busy} onClick={()=>{setSession(crypto.randomUUID());setRun(null);setAnswer('');runId.current='';pending.current=null;}}>{t('新会话')}</Button></Space>
  </Form></Card><Card title={t('调试结果')}><p className="op-muted">{t('SSE 逐字推送模型输出（model.delta），并在 run.completed 中返回完整回答；只展示 ReAct 最后一轮的答复。断线后使用 Last-Event-ID 重连事件接口。')}</p>{error&&<Alert type="error" showIcon title={error}/>}<Space wrap>{progress.map((p,i)=><Tag key={i}>{p}</Tag>)}</Space>{requestId&&<Typography.Paragraph copyable>Request ID: {requestId}</Typography.Paragraph>}{(run?.id||runId.current)&&<Typography.Paragraph copyable>Run ID: {run?.id||runId.current}</Typography.Paragraph>}{run&&<Tag>{run.status}</Tag>}<pre className="op-answer">{live||answer}</pre>{(run?.id||runId.current)&&<div className="op-answer-trace"><Button type="text" size="small" icon={<ToolOutlined aria-hidden/>} aria-label={t('查看运行轨迹')} title={t('查看运行轨迹')} onClick={()=>setTraceRun(run?.id||runId.current)}/></div>}</Card><Modal open={!!traceRun} width={920} title={t('运行详情')} onCancel={()=>setTraceRun('')} footer={<Button onClick={()=>setTraceRun('')}>{t('关闭')}</Button>}><Trace runId={traceRun}/></Modal></div>;
}
