import { useState } from 'react';
import { Alert, Button, Checkbox, Input, Modal, Radio, Table } from 'antd';
import { t, errorText } from '../../i18n';
import { post } from '../../shared/api/client';
import { EditField } from './WorkspaceForms';
import { ROOT, type Collection, type ToolApi } from './workspaceTypes';
interface ImportedApi { method:'GET'|'POST';name:string;display_name:string;description:string;relative_path:string;parameters:Record<string,unknown> }
interface ImportPreview {name:string;description:string;base_url:string;items:ImportedApi[];skipped:{path:string;method:string;reason:string}[];truncated:boolean}
export function ImportDialog({group,onClose,onSaved}:{group?:Collection;onClose:()=>void;onSaved:(id:string)=>void}) {
  const [preview,setPreview]=useState<ImportPreview|null>(null);const [name,setName]=useState('');const [base,setBase]=useState(group?.spec.url||'');const [selected,setSelected]=useState<React.Key[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function read(file:File){setBusy(true);setError('');setPreview(null);try{if(file.size>1_000_000)throw Error(t('文件不能超过 1 MB'));const p=await post<ImportPreview>(`${ROOT}/import/preview`,{content:await file.text()});setPreview(p);setName(p.name);if(!group)setBase(p.base_url);setSelected(p.items.map(a=>a.name));}catch(e){setError(errorText((e as Error).message))}finally{setBusy(false)}}
  async function save(){if(!preview)return;setBusy(true);setError('');try{const apis=preview.items.filter(a=>selected.includes(a.name)).map(a=>({display_name:a.display_name,relative_path:a.relative_path,auth_mode:'inherit',definition:{name:a.name,description:a.description,url:base.replace(/\/$/,'')+a.relative_path,parameters:a.parameters,method:a.method}}));const result=await post<{collection_id:string}>(`${ROOT}/import`,{...(group?{collection_id:group.id}:{collection:{name,description:preview.description,base_url:base,header_secrets:{}}}),apis});onSaved(result.collection_id)}catch(e){setError(errorText((e as Error).message))}finally{setBusy(false)}}
  return <Modal open width={850} title={t('导入 OpenAPI')} onCancel={()=>{if(!busy)onClose()}} footer={<><Button disabled={busy} onClick={onClose}>{t('取消')}</Button><Button type="primary" loading={busy} disabled={!preview||!selected.length} onClick={()=>void save()}>{t('导入为草稿')}</Button></>}><div className="tw-form">{error&&<Alert type="error" title={error}/>}<EditField label={t('定义文件（JSON / YAML）')}><Input type="file" accept=".json,.yaml,.yml" onChange={e=>{if(e.target.files?.[0])void read(e.target.files[0])}}/></EditField><Alert type="info" title={t('只导入选中的 GET / POST 接口，不导入密钥，不自动发布。')}/>{preview&&<>{!group&&<div className="tw-two"><EditField label={t('工具集名称')}><Input value={name} maxLength={64} onChange={e=>setName(e.target.value)}/></EditField><EditField label={t('服务地址')}><Input type="url" value={base} onChange={e=>setBase(e.target.value)}/></EditField></div>}<Table rowKey="name" size="small" scroll={{x:500}} dataSource={preview.items} rowSelection={{selectedRowKeys:selected,onChange:setSelected}} columns={[{title:t('调用标识'),dataIndex:'name',render:(v,record)=><Input value={v} onChange={e=>{const next=e.target.value;setSelected(selected.map(k=>k===v?next:k));setPreview({...preview,items:preview.items.map(a=>a===record?{...a,name:next}:a)})}}/>},{title:t('API 名称'),dataIndex:'display_name'},{title:t('方法'),dataIndex:'method'},{title:t('路径'),dataIndex:'relative_path'}]}/>{preview.truncated&&<Alert type="warning" title={t('最多导入 100 个 API，请拆分文件。')}/>}<details><summary>{t('未支持的接口')}（{preview.skipped.length}）</summary><Table rowKey={r=>r.path+r.method} size="small" dataSource={preview.skipped} columns={[{title:t('方法'),dataIndex:'method'},{title:t('路径'),dataIndex:'path'},{title:t('原因'),dataIndex:'reason'}]}/></details></>}</div></Modal>;
}
export function TestDialog({group,value,onClose}:{group:Collection;value:ToolApi;onClose:()=>void}) {
  const [confirmed,setConfirmed]=useState(false);const [mode,setMode]=useState('simulation');const [args,setArgs]=useState('{}');const [response,setResponse]=useState('{}');const [result,setResult]=useState<unknown>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function run(){setBusy(true);setError('');setResult(null);try{setResult(await post(`${ROOT}/apis/${value.id}/test`,{mode,confirmed,arguments:JSON.parse(args),response:mode==='simulation'?JSON.parse(response):null,revision:value.revision,collection_revision:group.revision}))}catch(e){setError(errorText((e as Error).message))}finally{setBusy(false)}}
  return <Modal open width={720} title={`${t('调试 API')} · ${value.display_name}`} onCancel={()=>{if(!busy)onClose()}} footer={<><Button disabled={busy} onClick={onClose}>{t('关闭')}</Button><Button type="primary" loading={busy} disabled={mode==='live'&&value.spec.method==='POST'&&!confirmed} onClick={()=>void run()}>{mode==='simulation'?t('检查 Schema'):t('发送 {{method}} 请求',{method:value.spec.method||'GET'})}</Button></>}><div className="tw-form">{error&&<Alert type="error" title={error}/>}<Radio.Group value={mode} onChange={e=>{setMode(e.target.value);setResult(null);setConfirmed(false)}} options={[{value:'simulation',label:t('模拟检查')},{value:'live',label:t('真实试调用')}]}/><Alert type={mode==='simulation'?'info':'warning'} title={mode==='simulation'?t('仅校验参数与模拟响应，不请求上游。'):t('将携带已保存的鉴权，向当前接口发送真实 {{method}} 请求。',{method:value.spec.method||'GET'})}/>{mode==='live'&&value.spec.method==='POST'&&<Checkbox checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}>{t('我确认发送此 POST 请求，接口可能修改业务数据。')}</Checkbox>}<EditField label={t('参数 JSON')}><Input.TextArea className="tw-code" rows={5} value={args} onChange={e=>setArgs(e.target.value)}/></EditField>{mode==='simulation'&&<EditField label={t('模拟响应 JSON')}><Input.TextArea className="tw-code" rows={4} value={response} onChange={e=>setResponse(e.target.value)}/></EditField>}{result!==null&&<pre className="tw-test-result">{JSON.stringify(result,null,2)}</pre>}</div></Modal>;
}
